image: alpine:latest

# ---------------------------------------
# Global
# ---------------------------------------

stages:
  - "Build"
  - "Tests"
  - "Unit Tests"
  - "Integration Tests"
  - "Deploy"

variables:
  CI: "true"

# ----------------------------------------
# Prescript
# ----------------------------------------

# ----------------------------------------
# Build
# ----------------------------------------

build:
  stage: "Build"
  image: davidhrbac/docker-shellcheck
  script:
    - sh build/lint.sh
  only:
    - web
    - develop
    - master

# ----------------------------------------
# Tests
# ----------------------------------------

test-entrypoint:
  stage: "Tests"
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/entrypoint/run.sh
  dependencies:
    - build
  only:
    - web
    - develop
    - master

test-unit:
  stage: "Unit Tests"
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/unit/run.sh
  dependencies:
    - build
  only:
    - web
    - develop
    - master

test-integration:
  stage: "Integration Tests"
  image: jrbeverly/bats:baseimage
  script:
    - sh .docker/provision.sh
    - sh tests/integration/run.sh
  dependencies:
    - build
  only:
    - web
    - develop
    - master

# ----------------------------------------
# Deploy
# ----------------------------------------

deploy:
  stage: "Deploy"
  script:
    - apk add -U zip
    - sh build/package.sh
  artifacts:
    expire_in: 4 weeks
    paths:
      - out/githooks*.zip
  only:
    - web
    - master