stages:
  - build

build:
    image: jrbeverly/pdf2htmlex:baseimage
    stage: build
    script:
        - pdf2htmlEX --zoom 1.5 --embed cfijo --dest-dir public/ index.pdf
    only:
        - triggers
        - master
    artifacts:
        paths:
            - public
        expire_in: 2 hours