stages:
  - build

build:
  stage: build
  image: jrbeverly/minify:baseimage
  script:
    - minify -o index-min.html index.html
  only: 
    - master
  artifacts:
    paths:
      - public/
    expire_in: 1 hour