image: jrbeverly/rsvg:baseimage

stages:
  - build
  
convert:
  stage: build
  script:
    - rsvg-convert -h 200 -f svg "icon.svg" > "out/icon.svg"
    - rsvg-convert -h 200 -f png "icon.svg" > "out/icon.png"
  only:
    - master
  artifacts:
    paths:
      - output/*
    expire_in: 4 weeks