stages:
  - "Integration Tests"

test-integration:
  stage: "Integration Tests"
  image: jrbeverly/bats:baseimage
  script:
    - "shellcheck --shell=sh script.sh && echo Passed: $hookname/$scriptname"
  dependencies:
    - build
  only:
    - web
    - develop
    - master