image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  STAGING_REGISTRY: registry.gitlab.com
  STAGING_NAMESPACE: myProject
  STAGING_PROJECT: myImage

  #STAGING_IMAGE := ${STAGING_REGISTRY}/${STAGING_NAMESPACE}/${STAGING_PROJECT}
  #WORKING_IMAGE ?= $(STAGING_IMAGE):$(TAG_PREFIX)$(TAG)$(TAG_SUFFIX)

  REGISTRY: docker.io
  NAMESPACE: myProject
  PROJECT: myImage

  GIT_COMMIT: ${CI_COMMIT_SHA}
  TAG_PREFIX: ${CI_PIPELINE_ID}-

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $STAGING_REGISTRY
  - apk --update-cache add make

build:
  stage: build
  variables:
    VERSION: baseimage
  script:
    - docker build --pull -t hello-world
  only:
    - web
    - master